-- MySQL Script generated by MySQL Workbench
-- Sun Jul  1 21:29:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema usermanager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usermanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usermanager` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`Anrede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Anrede` (
  `id` INT NOT NULL,
  `anrede` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Benutzer` (
  `id` INT NOT NULL,
  `vorname` VARCHAR(45) NULL,
  `nachname` VARCHAR(45) NULL,
  `benutzername` VARCHAR(45) NULL,
  `passwort` VARCHAR(45) NULL,
  `Anrede_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Anrede_id`),
  INDEX `fk_Benutzer_Anrede_idx` (`Anrede_id` ASC),
  CONSTRAINT `fk_Benutzer_Anrede`
    FOREIGN KEY (`Anrede_id`)
    REFERENCES `test`.`Anrede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `usermanager` ;

-- -----------------------------------------------------
-- Table `usermanager`.`anrede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usermanager`.`anrede` (
  `anrede` VARCHAR(100) NOT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usermanager`.`benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usermanager`.`benutzer` (
  `admin` VARCHAR(5) NOT NULL,
  `anredeID` INT(11) NOT NULL,
  `benutzername` VARCHAR(100) NOT NULL,
  `id` INT(11) NOT NULL,
  `nachname` VARCHAR(100) NOT NULL,
  `passwort` VARCHAR(100) NOT NULL,
  `vorname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usermanager`.`eo_pk_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usermanager`.`eo_pk_table` (
  `NAME` CHAR(40) NOT NULL,
  `PK` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
